/**
 * This code was generated by the Kepler Codegen tool.
 *
 * It is provided as a starting template and can be modified.
 *
 * @generated by GenerateModuleH.js
 */

#include "generated/DdRumSpec.h"

#include "AttributeConverter.h"
#include "DatadogGlobalState.h"
#include "EnumParsers.h"

namespace DdRumTurboModule {

class DdRum : public DdRumSpec {
public:
  DdRum();
  ~DdRum() noexcept;

  com::amazon::kepler::turbomodule::Promise startView(std::string key, std::string name, com::amazon::kepler::turbomodule::JSObject context, double timestampMs) override;
  com::amazon::kepler::turbomodule::Promise stopView(std::string key, com::amazon::kepler::turbomodule::JSObject context, double timestampMs) override;
  com::amazon::kepler::turbomodule::Promise startAction(std::string type, std::string name, com::amazon::kepler::turbomodule::JSObject context, double timestampMs) override;
  com::amazon::kepler::turbomodule::Promise stopAction(std::string type, std::string name, com::amazon::kepler::turbomodule::JSObject context, double timestampMs) override;
  com::amazon::kepler::turbomodule::Promise addAction(std::string type, std::string name, com::amazon::kepler::turbomodule::JSObject context, double timestampMs) override;
  com::amazon::kepler::turbomodule::Promise startResource(std::string key, std::string method, std::string url, com::amazon::kepler::turbomodule::JSObject context, double timestampMs) override;
  com::amazon::kepler::turbomodule::Promise stopResource(std::string key, double statusCode, std::string kind, double size, com::amazon::kepler::turbomodule::JSObject context, double timestampMs) override;
  com::amazon::kepler::turbomodule::Promise addError(std::string message, std::string source, std::string stacktrace, com::amazon::kepler::turbomodule::JSObject context, double timestampMs, std::string fingerprint) override;
  com::amazon::kepler::turbomodule::Promise addTiming(std::string name) override;
  com::amazon::kepler::turbomodule::Promise addViewAttribute(std::string key, com::amazon::kepler::turbomodule::JSObject value) override;
  com::amazon::kepler::turbomodule::Promise removeViewAttribute(std::string key) override;
  com::amazon::kepler::turbomodule::Promise addViewAttributes(com::amazon::kepler::turbomodule::JSObject attributes) override;
  com::amazon::kepler::turbomodule::Promise removeViewAttributes(std::vector<std::string> keys) override;
  com::amazon::kepler::turbomodule::Promise addViewLoadingTime(bool overwrite) override;
  com::amazon::kepler::turbomodule::Promise stopSession() override;
  com::amazon::kepler::turbomodule::Promise addFeatureFlagEvaluation(std::string name, com::amazon::kepler::turbomodule::JSObject value) override;
  com::amazon::kepler::turbomodule::Promise getCurrentSessionId() override;
  com::amazon::kepler::turbomodule::Promise startFeatureOperation(std::string name, std::string operationKey, com::amazon::kepler::turbomodule::JSObject attributes) override;
  com::amazon::kepler::turbomodule::Promise succeedFeatureOperation(std::string name, std::string operationKey, com::amazon::kepler::turbomodule::JSObject attributes) override;
  com::amazon::kepler::turbomodule::Promise failFeatureOperation(std::string name, std::string operationKey, std::string reason, com::amazon::kepler::turbomodule::JSObject attributes) override;
};

} // namespace DdRumTurboModule
