/**
 * This code was generated by the Kepler Codegen tool.
 *
 * It is provided as a starting template and can be modified.
 *
 * @generated by GenerateModuleCpp.js
 */

#include "DdRum.h"

#include <memory>
#include <string>
#include <thread>

#include "datadog/rum.hpp"

using namespace com::amazon::kepler::turbomodule;

namespace DdRumTurboModule {

DdRum::DdRum() {}
DdRum::~DdRum() noexcept {}

com::amazon::kepler::turbomodule::Promise DdRum::startView(
    std::string key,
    std::string name,
    com::amazon::kepler::turbomodule::JSObject context,
    double timestampMs
) {
    return Promise([key, name, context](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, key, name, context]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->StartView(key, name, datadog_rn_vega::jsObjectToAttribute(context));
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::stopView(
    std::string key,
    com::amazon::kepler::turbomodule::JSObject context,
    double timestampMs
) {
    return Promise([key, context](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, key, context]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->StopView(key, datadog_rn_vega::jsObjectToAttribute(context));
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::startAction(
    std::string type,
    std::string name,
    com::amazon::kepler::turbomodule::JSObject context,
    double timestampMs
) {
    return Promise([type, name, context](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, type, name, context]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->StartAction(
                    datadog_rn_vega::parseActionType(type),
                    name,
                    datadog_rn_vega::jsObjectToAttribute(context)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::stopAction(
    std::string type,
    std::string name,
    com::amazon::kepler::turbomodule::JSObject context,
    double timestampMs
) {
    return Promise([type, name, context](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, type, name, context]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->StopAction(
                    datadog_rn_vega::parseActionType(type),
                    name,
                    datadog_rn_vega::jsObjectToAttribute(context)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::addAction(
    std::string type,
    std::string name,
    com::amazon::kepler::turbomodule::JSObject context,
    double timestampMs
) {
    return Promise([type, name, context](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, type, name, context]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->AddAction(
                    datadog_rn_vega::parseActionType(type),
                    name,
                    datadog_rn_vega::jsObjectToAttribute(context)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::startResource(
    std::string key,
    std::string method,
    std::string url,
    com::amazon::kepler::turbomodule::JSObject context,
    double timestampMs
) {
    return Promise([key, method, url, context](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, key, method, url, context]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->StartResource(
                    key,
                    datadog_rn_vega::parseResourceMethod(method),
                    url,
                    datadog_rn_vega::jsObjectToAttribute(context)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::stopResource(
    std::string key,
    double statusCode,
    std::string kind,
    double size,
    com::amazon::kepler::turbomodule::JSObject context,
    double timestampMs
) {
    return Promise([key, statusCode, kind, size, context](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, key, statusCode, kind, size, context]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->StopResource(
                    key,
                    static_cast<int32_t>(statusCode),
                    static_cast<int64_t>(size),
                    datadog_rn_vega::parseResourceType(kind),
                    datadog_rn_vega::jsObjectToAttribute(context)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::addError(
    std::string message,
    std::string source,
    std::string stacktrace,
    com::amazon::kepler::turbomodule::JSObject context,
    double timestampMs,
    std::string fingerprint
) {
    return Promise([message, source, stacktrace, context](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, message, source, stacktrace, context]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->AddError(
                    datadog_rn_vega::parseErrorSource(source),
                    message,
                    /*type=*/"",
                    stacktrace,
                    datadog_rn_vega::jsObjectToAttribute(context)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::addTiming(std::string name) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: addTiming is not supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::addViewAttribute(
    std::string key,
    com::amazon::kepler::turbomodule::JSObject value
) {
    return Promise([key, value](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, key, value]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->AddViewAttribute(key, datadog_rn_vega::jsObjectToAttribute(value));
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::removeViewAttribute(std::string key) {
    return Promise([key](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, key]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->RemoveViewAttribute(key);
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::addViewAttributes(
    com::amazon::kepler::turbomodule::JSObject attributes
) {
    return Promise([attributes](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, attributes]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                for (const auto& entry : attributes) {
                    rum->AddViewAttribute(
                        entry.first,
                        datadog_rn_vega::jsValueToAttribute(entry.second)
                    );
                }
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::removeViewAttributes(
    std::vector<std::string> keys
) {
    return Promise([keys](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, keys]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                for (const auto& key : keys) {
                    rum->RemoveViewAttribute(key);
                }
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::addViewLoadingTime(bool overwrite) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: addViewLoadingTime is not supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::stopSession() {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->StopSession();
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::addFeatureFlagEvaluation(
    std::string name,
    com::amazon::kepler::turbomodule::JSObject value
) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: addFeatureFlagEvaluation is not supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::getCurrentSessionId() {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // dd-sdk-cpp does not expose session ID through its public API.
            // Session IDs are generated internally and included in all RUM events.
            promise->resolve(std::string(""));
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::startFeatureOperation(
    std::string name,
    std::string operationKey,
    com::amazon::kepler::turbomodule::JSObject attributes
) {
    return Promise([name, operationKey, attributes](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, name, operationKey, attributes]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->StartOperation(
                    name,
                    operationKey,
                    datadog_rn_vega::jsObjectToAttribute(attributes)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::succeedFeatureOperation(
    std::string name,
    std::string operationKey,
    com::amazon::kepler::turbomodule::JSObject attributes
) {
    return Promise([name, operationKey, attributes](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, name, operationKey, attributes]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->SucceedOperation(
                    name,
                    operationKey,
                    datadog_rn_vega::jsObjectToAttribute(attributes)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdRum::failFeatureOperation(
    std::string name,
    std::string operationKey,
    std::string reason,
    com::amazon::kepler::turbomodule::JSObject attributes
) {
    return Promise([name, operationKey, reason, attributes](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, name, operationKey, reason, attributes]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->FailOperation(
                    name,
                    datadog_rn_vega::parseOperationFailureReason(reason),
                    operationKey,
                    datadog_rn_vega::jsObjectToAttribute(attributes)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

} // namespace DdRumTurboModule
