/**
 * This code was generated by the Kepler Codegen tool.
 *
 * It is provided as a starting template and can be modified.
 *
 * @generated by GenerateModuleH.js
 */

#include "generated/DdSdkSpec.h"

#include "AttributeConverter.h"
#include "DatadogGlobalState.h"
#include "EnumParsers.h"
#include "HttpJsProxy.h"

namespace DdSdkTurboModule {

class DdSdk : public DdSdkSpec {
public:
  DdSdk();
  ~DdSdk() noexcept;

  com::amazon::kepler::turbomodule::Promise initialize(com::amazon::kepler::turbomodule::JSObject configuration) override;
  com::amazon::kepler::turbomodule::Promise addAttribute(std::string key, com::amazon::kepler::turbomodule::JSObject value) override;
  com::amazon::kepler::turbomodule::Promise removeAttribute(std::string key) override;
  com::amazon::kepler::turbomodule::Promise addAttributes(com::amazon::kepler::turbomodule::JSObject attributes) override;
  com::amazon::kepler::turbomodule::Promise removeAttributes(std::vector<std::string> keys) override;
  com::amazon::kepler::turbomodule::Promise setUserInfo(com::amazon::kepler::turbomodule::JSObject user) override;
  com::amazon::kepler::turbomodule::Promise clearUserInfo() override;
  com::amazon::kepler::turbomodule::Promise addUserExtraInfo(com::amazon::kepler::turbomodule::JSObject extraInfo) override;
  com::amazon::kepler::turbomodule::Promise setAccountInfo(com::amazon::kepler::turbomodule::JSObject account) override;
  com::amazon::kepler::turbomodule::Promise clearAccountInfo() override;
  com::amazon::kepler::turbomodule::Promise addAccountExtraInfo(com::amazon::kepler::turbomodule::JSObject extraInfo) override;
  com::amazon::kepler::turbomodule::Promise setTrackingConsent(std::string trackingConsent) override;
  com::amazon::kepler::turbomodule::Promise sendTelemetryLog(std::string message, com::amazon::kepler::turbomodule::JSObject attributes, com::amazon::kepler::turbomodule::JSObject config) override;
  com::amazon::kepler::turbomodule::Promise telemetryDebug(std::string message) override;
  com::amazon::kepler::turbomodule::Promise telemetryError(std::string message, std::string stack, std::string kind) override;
  com::amazon::kepler::turbomodule::Promise consumeWebviewEvent(std::string message) override;
  com::amazon::kepler::turbomodule::Promise clearAllData() override;
  com::amazon::kepler::turbomodule::Promise httpResponse(std::string requestId, double statusCode) override;
  com::amazon::kepler::turbomodule::Promise crashForTesting() override;
};

} // namespace DdSdkTurboModule
