/**
 * This code was generated by the Kepler Codegen tool.
 *
 * It is provided as a starting template and can be modified.
 *
 * @generated by GenerateModuleCpp.js
 */

#include "DdSdk.h"

#include <filesystem>
#include <memory>
#include <string>
#include <thread>
#include <vector>

#include "datadog/core.hpp"
#include "datadog/rum.hpp"

using namespace com::amazon::kepler::turbomodule;

namespace DdSdkTurboModule {

// ---------------------------------------------------------------------------
// Helper utilities
// ---------------------------------------------------------------------------

namespace {

std::string getStringFromJSObject(
    const JSObject& obj,
    const std::string& key,
    const std::string& defaultVal = ""
) {
    auto it = obj.find(key);
    if (it != obj.end()) {
        if (auto* str = std::get_if<std::string>(&it->second)) {
            return *str;
        }
    }
    return defaultVal;
}

double getDoubleFromJSObject(
    const JSObject& obj,
    const std::string& key,
    double defaultVal = 0.0
) {
    auto it = obj.find(key);
    if (it != obj.end()) {
        if (auto* d = std::get_if<double>(&it->second)) {
            return *d;
        }
    }
    return defaultVal;
}

const JSObject* getObjectFromJSObject(
    const JSObject& obj,
    const std::string& key
) {
    auto it = obj.find(key);
    if (it != obj.end()) {
        if (auto* nested = std::get_if<JSObject>(&it->second)) {
            return nested;
        }
    }
    return nullptr;
}

}  // anonymous namespace

// ---------------------------------------------------------------------------
// DdSdk implementation
// ---------------------------------------------------------------------------

DdSdk::DdSdk() {}
DdSdk::~DdSdk() noexcept {}

com::amazon::kepler::turbomodule::Promise DdSdk::initialize(
    com::amazon::kepler::turbomodule::JSObject configuration
) {
    // Set up the HTTP JS proxy emit function.
    // 'this' (DdSdk) inherits emit() from KeplerTurboModule.
    // Capture 'this' — safe because DdSdk outlives the SDK core.
    datadog_rn_vega::HttpRequestBridge::getInstance().setEmitFunction(
        [this](const std::string& requestId, const std::string& url,
               const std::string& headers, const std::string& body) {
            JSObject payload;
            payload["requestId"] = requestId;
            payload["url"] = url;
            payload["headers"] = headers;
            payload["body"] = body;
            this->emit("ddHttpRequest", payload);
        });

    return Promise([configuration](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, configuration]() {
            // Extract top-level config values
            const std::string clientToken =
                getStringFromJSObject(configuration, "clientToken");
            const std::string env =
                getStringFromJSObject(configuration, "env");
            std::string serviceName =
                getStringFromJSObject(configuration, "service");
            if (serviceName.empty()) {
                serviceName = getStringFromJSObject(configuration, "serviceName");
            }
            if (serviceName.empty()) {
                serviceName = "com.datadog.reactnative.vega";
            }
            const std::string site =
                getStringFromJSObject(configuration, "site");
            const std::string trackingConsent =
                getStringFromJSObject(configuration, "trackingConsent");
            const std::string batchSize =
                getStringFromJSObject(configuration, "batchSize");
            const std::string uploadFrequency =
                getStringFromJSObject(configuration, "uploadFrequency");
            const std::string batchProcessingLevel =
                getStringFromJSObject(configuration, "batchProcessingLevel");
            const std::string version =
                getStringFromJSObject(configuration, "version");

            // Build CoreConfig
            datadog::CoreConfig coreConfig(clientToken, serviceName, env);

            // Override source to match React Native SDK conventions
            coreConfig.Internal_SetSource("react-native");

            if (!site.empty()) {
                coreConfig.SetSite(datadog_rn_vega::parseSite(site));
            }
            // Initial tracking consent is no longer a CoreConfig setter; it is passed
            // to Core::Create below. parseTrackingConsent defaults to Pending when the
            // value is empty/unrecognized.
            const datadog::TrackingConsent initialTrackingConsent =
                datadog_rn_vega::parseTrackingConsent(trackingConsent);
            if (!batchSize.empty()) {
                coreConfig.SetBatchSize(datadog_rn_vega::parseBatchSize(batchSize));
            }
            if (!uploadFrequency.empty()) {
                coreConfig.SetUploadFrequency(
                    datadog_rn_vega::parseUploadFrequency(uploadFrequency)
                );
            }
            if (!batchProcessingLevel.empty()) {
                coreConfig.SetBatchProcessingLevel(
                    datadog_rn_vega::parseBatchProcessingLevel(batchProcessingLevel)
                );
            }
            if (!version.empty()) {
                coreConfig.SetVersion(version);
            }

            // Probe for a writable directory on Vega
            // The app runs in a security sandbox so not all paths are accessible
            {
                std::vector<std::string> candidates = {
                    "/data",
                    "/tmp",
                    "/tmp/scratch",
                    "/var/tmp",
                    ".",
                };
                std::string chosen;
                for (const auto& path : candidates) {
                    std::string testDir = path + "/.datadog_probe";
                    std::error_code ec;
                    std::filesystem::create_directories(testDir, ec);
                    if (!ec) {
                        std::filesystem::remove(testDir, ec);
                        chosen = path;
                        break;
                    }
                }
                if (chosen.empty()) {
                    chosen = "/tmp";  // fallback, will likely fail
                }
                coreConfig.SetApplicationStoragePath(chosen);
            }

            // Create the Core (but don't Start yet — features must register first)
            auto core = datadog::Core::Create(coreConfig, initialTrackingConsent);
            if (!core) {
                promise->resolve(true);
                return;
            }
            datadog_rn_vega::DatadogGlobalState::getInstance().setCore(core);

            // Register features BEFORE calling Start()
            const JSObject* rumConfiguration =
                getObjectFromJSObject(configuration, "rumConfiguration");
            if (rumConfiguration != nullptr) {
                const std::string applicationId =
                    getStringFromJSObject(*rumConfiguration, "applicationId");
                const double sessionSampleRate =
                    getDoubleFromJSObject(*rumConfiguration, "sessionSampleRate", 100.0);

                if (!applicationId.empty()) {
                    datadog::RumConfig rumConfig(applicationId);
                    rumConfig.SetSessionSampleRate(
                        static_cast<float>(sessionSampleRate)
                    );

                    auto rum = datadog::Rum::Register(core, rumConfig);
                    if (rum) {
                        datadog_rn_vega::DatadogGlobalState::getInstance().setRum(rum);
                    }
                }
            }

            // Now Start the Core (after features are registered)
            core->Start();
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::addAttribute(
    std::string key,
    com::amazon::kepler::turbomodule::JSObject value
) {
    return Promise([key, value](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, key, value]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->AddAttribute(
                    key, datadog_rn_vega::jsWrappedValueToAttribute(value)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::removeAttribute(std::string key) {
    return Promise([key](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, key]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                rum->RemoveAttribute(key);
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::addAttributes(
    com::amazon::kepler::turbomodule::JSObject attributes
) {
    return Promise([attributes](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, attributes]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                for (const auto& entry : attributes) {
                    rum->AddAttribute(
                        entry.first,
                        datadog_rn_vega::jsValueToAttribute(entry.second)
                    );
                }
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::removeAttributes(
    std::vector<std::string> keys
) {
    return Promise([keys](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, keys]() {
            auto rum = datadog_rn_vega::DatadogGlobalState::getInstance().getRum();
            if (rum) {
                for (const auto& key : keys) {
                    rum->RemoveAttribute(key);
                }
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::setUserInfo(
    com::amazon::kepler::turbomodule::JSObject user
) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: user info not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::clearUserInfo() {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: user info not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::addUserExtraInfo(
    com::amazon::kepler::turbomodule::JSObject extraInfo
) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: user info not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::setAccountInfo(
    com::amazon::kepler::turbomodule::JSObject account
) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: account info not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::clearAccountInfo() {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: account info not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::addAccountExtraInfo(
    com::amazon::kepler::turbomodule::JSObject extraInfo
) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: account info not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::setTrackingConsent(
    std::string trackingConsent
) {
    return Promise([trackingConsent](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, trackingConsent]() {
            auto core = datadog_rn_vega::DatadogGlobalState::getInstance().getCore();
            if (core) {
                core->SetTrackingConsent(
                    datadog_rn_vega::parseTrackingConsent(trackingConsent)
                );
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::sendTelemetryLog(
    std::string message,
    com::amazon::kepler::turbomodule::JSObject attributes,
    com::amazon::kepler::turbomodule::JSObject config
) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: telemetry not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::telemetryDebug(std::string message) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: telemetry not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::telemetryError(
    std::string message,
    std::string stack,
    std::string kind
) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: telemetry not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::consumeWebviewEvent(
    std::string message
) {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            // No-op: webview events not yet supported in dd-sdk-cpp
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::clearAllData() {
    return Promise([](const std::shared_ptr<Promise>& promise) {
        std::thread([promise]() {
            auto core = datadog_rn_vega::DatadogGlobalState::getInstance().getCore();
            if (core) {
                // Best-effort clear: stop then restart
                core->Stop();
                core->Start();
            }
            promise->resolve(true);
        }).detach();
    });
}

com::amazon::kepler::turbomodule::Promise DdSdk::httpResponse(
    std::string requestId,
    double statusCode
) {
    return Promise([requestId, statusCode](const std::shared_ptr<Promise>& promise) {
        std::thread([promise, requestId, statusCode]() {
            datadog_rn_vega::HttpRequestBridge::getInstance()
                .onResponse(requestId, static_cast<int>(statusCode));
            promise->resolve(true);
        }).detach();
    });
}

}  // namespace DdSdkTurboModule
