require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'DdSdkReactNativeExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config["reactNativePath"],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # uncomment this line to use the local version of the iOS DatadogSDK
  # pod 'DatadogSDKBridge', :path => '../../../dd-bridge-ios/DatadogSDKBridge.podspec'

  # Make all the other frameworks into static frameworks by overriding the static_framework? function to return true
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name == "DatadogSDKReactNative"
        def pod.path
          '../../packages/core/DatadogSDKReactNative.podspec'
        end 
        def pod.testspecs
          ['Tests']
        end
      end
    end
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # Enable `DD_SDK_COMPILED_FOR_TESTING` condition when compiling `DatadogSDK` dependency:
    datadog_sdk_target = installer.pods_project.targets.detect {|t| t.name == "DatadogSDK" }
    datadog_sdk_target.build_configurations.each do |config|
      config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) DD_SDK_COMPILED_FOR_TESTING'
    end
  end
end
