require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
use_frameworks!

target 'DdSdkReactNativeExample' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # uncomment this line to use the local version of the iOS DatadogSDK
  # pod 'DatadogSDKBridge', :path => '../../../dd-bridge-ios/DatadogSDKBridge.podspec'
  pod 'dd-sdk-reactnative', :path => '../..'
end
