name: Publish packages on NPM
on:
    # release:
    #   types: [created]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
            - run: yarn config set npmAuthToken $NPM_PUBLISH_TOKEN --home # Uses --home to avoid updating the project's .yarnrc.yml
              env:
                  NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
            - run: yarn
            - run: yarn run lerna publish from-package
